with-expecter: true
dir: "mocks"
outpkg: "mocks"
mockname: "{{.InterfaceNameCamel}}"
filename: "{{.InterfaceNameSnake}}_mock.go"

packages:
  github.com/yuriyfomin17/largest-picture-nasa-api/internal/app/transport/httpserver:
    interfaces:
      MarsAPILargestPictureService: